Repository UWOrbital/OBC-firmware, pull requests merged in 2025-03, with the labels that each got.

#266 [BUGFIX] OBC SPI Driver - bus owner check
  obc/app/drivers/rm46/obc_spi_io.c
Labels: bug

#323 Add useful scripts
  README.md
  scripts/example-build.sh
  scripts/gs-build.sh
  scripts/obc-build.sh
  scripts/test.sh
Labels: documentation, enhancement

#329 Fix issue templates directory
  .github/ISSUE_TEMPLATE/bugs.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: bug, documentation

#330 Fix issue templates v2
  .github/ISSUE_TEMPLATE/bugs.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.md
Labels: bug, documentation

#331 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug, documentation

#327 Add logger middleware
  gs/backend/api/backend_setup.py
  gs/backend/api/middleware/logger_middleware.py
  requirements.txt
Labels: project: backend
